baseURL = 'https://timely-otter-8095e5.netlify.app/'
languageCode = 'en'
# languageCode = 'en'
theme = "JuiceBar"


[params]
author = ""
description = "PetaniBangkit"
authorImage = ""
paginate = 5

Title = "PetaniBangkit"
content = "Yuk support Petani Lokal Kita....!"
imageUrl = "/images/farmprofil.jpg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "whatsapp"
url = "https://wa.me/0881082450449"

[[params.social]]
name = "instagram"
url = "https://instagram.com/petanibangkit"

[[params.social]]
name = "facebook"
url = "https://facebook.com/petanibangkit"

[[params.social]]
name = "email"
url = "mailto:dimas@santricyber.com"

[[params.social]]
name = "youtube"
url = "https://www.petanibangkit.com/#"


[[params.mermaid]]
theme = "dark"
align = "center"



